export enum DexCore {
  ERR_UNKNOWN_FUNC,
  ERR_FUNC_SET,
  ERR_HIGH_FUNC_INDEX,
  ERR_CANT_UNPACK_LAMBDA,
  ERR_WRONG_PAIR_ORDER,
  ERR_ZERO_A_IN,
  ERR_ZERO_B_IN,
  ERR_PAIR_LISTED,
  ERR_PAIR_NOT_LISTED,
  ERR_NO_LIQUIDITY,
  ERR_NO_SHARES_EXPECTED,
  EER_LOW_TOKEN_A_IN,
  EER_LOW_TOKEN_B_IN,
  ERR_TEZ_STORE_404,
  ERR_INSUFFICIENT_LP,
  ERR_DUST_OUT,
  ERR_HIGH_MIN_OUT,
  ERR_TEZ_STORE_INVEST_TEZ_ENTRYPOINT_404,
  ERR_TEZ_STORE_DIVEST_TEZ_ENTRYPOINT_404,
}

export enum TezStore {
  ERR_NOT_DEX_CORE,
  ERR_INSUFFICIENT_TEZ_BALANCE,
}

export enum Common {
  ERR_NOT_ADMIN,
  ERR_NOT_PENDING_ADMIN,
  ERR_NOT_MANAGER,
  ERR_FA12_TRANSFER_ENTRYPOINT_404,
  ERR_FA2_TRANSFER_ENTRYPOINT_404,
}
